### ISSUE TITLE
Issues I'm facing.

### ISSUE THREAD

**Issue by arpkaz** [NaorNC/nc-loadingscreen#1]
Hi mate there is a couple of problems I am having with this loading screen:

1. When I want to copy any link to my clipboard, it doesn't actually copy anything and when you come to paste its just blank
2. The volume off/on does not work with the mp3, when you click start/stop it does not do anything. Same with the volume button.

Also I would recommend making the loading screen longer so that you don't load through the resources starting. (meaning the loading screen end as you actually spawn in). All in all though great script.

**Comment by NaorNC** [comment]
Hi, feel free to open a ticket for this on the discord server and I will be happy to help you.
